version: "3"

services:
  spa:
    container_name: spa
    build:
      context: .
      dockerfile: ./apps/spa/Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - app_network
  ssr:
    container_name: ssr
    build:
      context: .
      dockerfile: ./apps/ssr/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
